import type { Post } from "@/types/analytics"

export const mockPosts: Post[] = [
  {
    id: "1",
    platform: "Instagram",
    date: "2025-05-01T10:30:00",
    content:
      "Just launched our new AI-powered content creation tool! It helps businesses create engaging content 5x faster while maintaining brand consistency. #AIContent #ContentCreation",
    reach: 15420,
    likes: 842,
    comments: 156,
    shares: 78,
    engagementRate: 0.07,
  },
  {
    id: "2",
    platform: "LinkedIn",
    date: "2025-05-03T14:00:00",
    content:
      "The future of content creation is here. Our platform uses advanced AI to understand your brand voice and generate content that sounds just like you. Try it today!",
    reach: 8750,
    likes: 423,
    comments: 87,
    shares: 132,
    engagementRate: 0.073,
  },
  {
    id: "3",
    platform: "Facebook",
    date: "2025-05-05T09:00:00",
    content:
      "Content creation shouldn't be a bottleneck for your marketing team. Our AI tool helps you scale your content strategy without sacrificing quality or authenticity.",
    reach: 12680,
    likes: 567,
    comments: 98,
    shares: 215,
    engagementRate: 0.069,
  },
  {
    id: "4",
    platform: "X",
    date: "2025-05-07T16:45:00",
    content:
      "Wondering how AI can transform your content strategy? Join our webinar next week to learn how businesses are saving 15+ hours per week with our platform.",
    reach: 9870,
    likes: 312,
    comments: 45,
    shares: 187,
    engagementRate: 0.055,
  },
  {
    id: "5",
    platform: "Instagram",
    date: "2025-05-10T11:15:00",
    content:
      "Consistency is key in building a strong brand. Our AI ensures your content maintains a consistent voice across all channels, even when multiple team members are involved.",
    reach: 17680,
    likes: 978,
    comments: 203,
    shares: 92,
    engagementRate: 0.072,
  },
  {
    id: "6",
    platform: "LinkedIn",
    date: "2025-05-12T13:30:00",
    content:
      "We're excited to announce our integration with major social media platforms! Now you can create and schedule content all in one place.",
    reach: 11240,
    likes: 534,
    comments: 112,
    shares: 178,
    engagementRate: 0.073,
  },
  {
    id: "7",
    platform: "Facebook",
    date: "2025-05-15T10:00:00",
    content:
      "Quality content at scale is no longer a pipe dream. Our AI analyzes your best-performing content to create more of what your audience loves.",
    reach: 14520,
    likes: 687,
    comments: 124,
    shares: 231,
    engagementRate: 0.072,
  },
  {
    id: "8",
    platform: "X",
    date: "2025-05-18T15:20:00",
    content:
      "Behind every great brand is a consistent voice. Our AI helps you maintain that voice across all your content, no matter who's creating it.",
    reach: 8950,
    likes: 287,
    comments: 39,
    shares: 156,
    engagementRate: 0.054,
  },
  {
    id: "9",
    platform: "Instagram",
    date: "2025-05-20T09:45:00",
    content:
      "ROI matters. Our customers report a 40% increase in engagement after implementing our AI content creation tools. #ContentMarketing",
    reach: 19870,
    likes: 1023,
    comments: 187,
    shares: 104,
    engagementRate: 0.066,
  },
  {
    id: "10",
    platform: "LinkedIn",
    date: "2025-05-22T11:00:00",
    content:
      "We believe AI should enhance human creativity, not replace it. That's why our platform focuses on collaboration between AI and content creators.",
    reach: 10680,
    likes: 498,
    comments: 103,
    shares: 145,
    engagementRate: 0.07,
  },
  {
    id: "11",
    platform: "Facebook",
    date: "2025-05-25T14:30:00",
    content:
      "Content that resonates with your audience doesn't happen by accident. Our AI analyzes engagement patterns to help you create more of what works.",
    reach: 13750,
    likes: 623,
    comments: 118,
    shares: 198,
    engagementRate: 0.068,
  },
  {
    id: "12",
    platform: "X",
    date: "2025-05-27T16:00:00",
    content:
      "Time is your most valuable resource. Our AI content creation tool gives you back hours each week while improving your content quality.",
    reach: 7890,
    likes: 245,
    comments: 32,
    shares: 143,
    engagementRate: 0.053,
  },
  {
    id: "13",
    platform: "Instagram",
    date: "2025-05-29T12:15:00",
    content:
      "The secret to social media success? Consistency, quality, and authenticity. Our AI helps you achieve all three without the burnout.",
    reach: 16540,
    likes: 876,
    comments: 165,
    shares: 87,
    engagementRate: 0.068,
  },
  {
    id: "14",
    platform: "LinkedIn",
    date: "2025-05-31T10:30:00",
    content:
      "Join us for a live demo this Friday to see how our AI content creation platform can transform your marketing strategy. Register now!",
    reach: 9870,
    likes: 412,
    comments: 94,
    shares: 156,
    engagementRate: 0.067,
  },
  {
    id: "15",
    platform: "Facebook",
    date: "2025-06-02T09:00:00",
    content:
      "Our AI doesn't just create content—it learns from your audience's engagement to continuously improve its outputs. The result? Better content and better results over time.",
    reach: 11980,
    likes: 543,
    comments: 107,
    shares: 187,
    engagementRate: 0.07,
  },
  {
    id: "16",
    platform: "X",
    date: "2025-06-04T15:45:00",
    content:
      "Content creation bottlenecks are a thing of the past. With our AI platform, you can produce a week's worth of content in under an hour.",
    reach: 8450,
    likes: 267,
    comments: 35,
    shares: 132,
    engagementRate: 0.051,
  },
  {
    id: "17",
    platform: "Instagram",
    date: "2025-06-06T11:30:00",
    content:
      "Your brand has a unique voice. Our AI learns that voice and helps you maintain it consistently across all your content and channels.",
    reach: 18760,
    likes: 945,
    comments: 178,
    shares: 95,
    engagementRate: 0.065,
  },
  {
    id: "18",
    platform: "LinkedIn",
    date: "2025-06-08T13:00:00",
    content:
      "We're thrilled to announce our new enterprise plan, designed for marketing teams that need to scale their content creation without sacrificing quality.",
    reach: 10540,
    likes: 487,
    comments: 98,
    shares: 167,
    engagementRate: 0.071,
  },
  {
    id: "19",
    platform: "Facebook",
    date: "2025-06-10T10:15:00",
    content:
      "The most successful brands post consistently. Our AI makes that possible, even for small teams with limited resources.",
    reach: 12870,
    likes: 598,
    comments: 112,
    shares: 203,
    engagementRate: 0.071,
  },
  {
    id: "20",
    platform: "X",
    date: "2025-06-12T16:30:00",
    content:
      "AI-powered content creation isn't the future—it's the present. Don't get left behind. Try our platform today and see the difference.",
    reach: 7650,
    likes: 234,
    comments: 29,
    shares: 128,
    engagementRate: 0.051,
  },
  {
    id: "21",
    platform: "Instagram",
    date: "2025-06-15T12:45:00",
    content:
      "Our AI doesn't replace your creativity—it amplifies it. Think of it as your always-on, never-tired content creation partner.",
    reach: 15980,
    likes: 834,
    comments: 156,
    shares: 82,
    engagementRate: 0.067,
  },
  {
    id: "22",
    platform: "LinkedIn",
    date: "2025-06-17T14:15:00",
    content:
      "Content creation at scale used to require a large team and budget. Our AI changes that equation, making quality content accessible to businesses of all sizes.",
    reach: 9780,
    likes: 423,
    comments: 87,
    shares: 154,
    engagementRate: 0.068,
  },
  {
    id: "23",
    platform: "Facebook",
    date: "2025-06-20T09:30:00",
    content:
      "The brands that stand out are the ones that show up consistently. Our AI helps you maintain a consistent presence across all your channels.",
    reach: 13450,
    likes: 612,
    comments: 115,
    shares: 195,
    engagementRate: 0.069,
  },
  {
    id: "24",
    platform: "X",
    date: "2025-06-22T15:00:00",
    content:
      "Content creation shouldn't be a full-time job. Our AI gives you back your time while improving your results.",
    reach: 8120,
    likes: 256,
    comments: 33,
    shares: 138,
    engagementRate: 0.053,
  },
  {
    id: "25",
    platform: "Instagram",
    date: "2025-06-25T11:45:00",
    content:
      "Your audience craves authenticity. Our AI helps you create content that feels genuine and resonates with your followers.",
    reach: 17340,
    likes: 912,
    comments: 172,
    shares: 91,
    engagementRate: 0.068,
  },
  {
    id: "26",
    platform: "LinkedIn",
    date: "2025-06-27T13:30:00",
    content:
      "We're excited to share that our AI content platform now supports 12 languages! Create and translate content seamlessly for global audiences.",
    reach: 10230,
    likes: 467,
    comments: 95,
    shares: 163,
    engagementRate: 0.071,
  },
  {
    id: "27",
    platform: "Facebook",
    date: "2025-06-29T10:00:00",
    content:
      "The most effective content strategies are data-driven. Our AI analyzes performance metrics to continuously refine and improve your content.",
    reach: 12560,
    likes: 578,
    comments: 109,
    shares: 192,
    engagementRate: 0.07,
  },
  {
    id: "28",
    platform: "X",
    date: "2025-07-01T16:15:00",
    content:
      "AI-powered content creation is revolutionizing marketing. Join the revolution and see how our platform can transform your strategy.",
    reach: 7890,
    likes: 243,
    comments: 31,
    shares: 135,
    engagementRate: 0.052,
  },
  {
    id: "29",
    platform: "Instagram",
    date: "2025-07-03T12:30:00",
    content:
      "Quality and quantity don't have to be mutually exclusive. Our AI helps you achieve both without burning out your team.",
    reach: 16780,
    likes: 867,
    comments: 163,
    shares: 86,
    engagementRate: 0.067,
  },
  {
    id: "30",
    platform: "LinkedIn",
    date: "2025-07-05T14:45:00",
    content:
      "We're proud to announce that our AI content platform has been recognized as a leader in the G2 Grid for Content Creation Software!",
    reach: 11450,
    likes: 534,
    comments: 112,
    shares: 187,
    engagementRate: 0.073,
  },
]
